import type { Metadata } from "next";

import AppWrapper from "./AppWrapper";
import ErrorFallback from "./ErrorFallback";
import ThemeRegistry from "./theme/ThemeRegistry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <AppWrapper errorFallback={<ErrorFallback />}>{children}</AppWrapper>
        </ThemeRegistry>
      </body>
    </html>
  );
}
